### ISSUE TITLE
Discussion about future directions

### ISSUE THREAD

**Issue by alielfilali01** [ARBML/Taqyim#3]
Hello! I'm interested to know if there are any upcoming plans to broaden the Taqyim library by incorporating open-source models from the Hugging Face hub. Additionally, I noticed that the paper mentions 7 reported tasks, but it seems I can only test on 5 tasks at the moment. Is there a specific reason for not including paraphrasing and transliteration at the moment?

**Comment by zaidalyafeai** [comment]
Currently there are no plans to expand to other models. Regarding the tasks, transliteration and paraphrasing are considered a machine translation task because they have the same format and evaluation metrics.
